# Generated by Django 4.2.11 on 2026-08-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy', '0007_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='ai_analysis',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
